# Makefile for asst2

TOP=../../..
.include "$(TOP)/mk/os161.config.mk"

PROG=__mymytest
SRCS=__mymytest.c __mymytest_open.c __mymytest_close.c __mymytest_write.c __mymytest_read.c __mymytest_lseek.c __mymytest_dup2.c
BINDIR=/testbin

.include "$(TOP)/mk/os161.prog.mk"



